import type { BoardIssue } from '@/lib/api/endpoints/issues';
import type { ProjectDetail } from '@/lib/api/endpoints/projects';
import type { Permissions, ResourcePermissions } from '@/lib/api/endpoints/roles';

const readOnly: ResourcePermissions = { read: true, create: false, edit: false, delete: false };

const permissions = {
  work_items: { ...readOnly },
  initiatives: readOnly,
  cycles: readOnly,
  dashboards: readOnly,
  documents: readOnly,
  views: readOnly,
  members_invite: readOnly,
  members_manage: readOnly,
  states: readOnly,
  issue_types: readOnly,
  labels: readOnly,
  ai_agents: readOnly,
  integrations: readOnly,
  agent_skills: readOnly,
  agent_tools: readOnly,
  custom_fields: readOnly,
  issue_templates: readOnly,
  workflow_config: readOnly,
  actions: readOnly,
  webhooks: readOnly,
  note_boards: readOnly,
  danger_zone: readOnly,
} as Permissions;

function issue(id: number, columnId: number, parentId: number | null): BoardIssue {
  return {
    id,
    projectId: 1,
    sequenceNumber: id,
    identifier: `TEST-${id}`,
    title: `Issue ${id}`,
    columnId,
    parentId,
    typeId: null,
    initiative: null,
    cycle: null,
    assigneeUserId: null,
    delegateUserId: null,
    description: '',
    priority: null,
    estimatePoints: null,
    estimateMinutes: null,
    loggedMinutes: 0,
    startDate: null,
    dueDate: null,
    position: id,
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-01-01T00:00:00Z',
    archivedAt: null,
    statusSince: '2026-01-01T00:00:00Z',
    shareToken: null,
    shareExtended: false,
    labelIds: [],
    fieldValues: [],
    links: [],
    subtaskCount: id === 1 ? 2 : 0,
  };
}

export function projectFixture(): ProjectDetail {
  return {
    project: {
      id: 1,
      teamId: 1,
      teamName: 'Test',
      key: 'TEST',
      name: 'Test',
      description: '',
      createdAt: '2026-01-01T00:00:00Z',
      mcpEnabled: false,
      teamMcpEnabled: false,
      initiativesEnabled: true,
      dashboardsEnabled: true,
      documentsEnabled: true,
      notesEnabled: true,
      cyclesEnabled: true,
      subtasksEnabled: true,
      checklistsEnabled: true,
      issueStatsEnabled: true,
      availableFeatures: [
        'initiatives',
        'cycles',
        'dashboards',
        'documents',
        'notes',
        'subtasks',
        'checklists',
        'issueStats',
      ],
      pointsEstimateEnabled: false,
      timeEstimateEnabled: false,
      timeLoggingEnabled: false,
    },
    issues: [issue(1, 1, null), issue(2, 1, 1), issue(3, 2, 1)],
    columns: [
      {
        id: 1,
        projectId: 1,
        name: 'In progress',
        stateType: 'started',
        color: '#f59e0b',
        position: 0,
        wipLimit: null,
        wipMode: 'soft',
        autoAssignUserId: null,
      },
      {
        id: 2,
        projectId: 1,
        name: 'Done',
        stateType: 'completed',
        color: '#22c55e',
        position: 1,
        wipLimit: null,
        wipMode: 'soft',
        autoAssignUserId: null,
      },
    ],
    viewer: { role: 'member', teamRole: 'member' },
    permissions,
    issueTypes: [],
    labels: [],
    labelGroups: [],
    assignees: [],
    customFields: [],
    issueTemplates: [],
    plannedCycles: [],
  };
}
