import {
  Archive,
  ArchiveRestore,
  Calendar,
  CircleDot,
  CirclePlus,
  FileText,
  GitPullRequest,
  Link2,
  ListChecks,
  ListTree,
  Pencil,
  RefreshCw,
  Shapes,
  SignalHigh,
  Bot,
  Tag,
  UserRound,
  type LucideIcon,
} from 'lucide-react';
import { type ActivityAction } from '@/lib/api';

// The icon of each activity feed event. Its verb phrase is built by
// useActivityText, which needs the reader's language.

export const ACTION_ICON: Record<ActivityAction, LucideIcon> = {
  created: CirclePlus,
  title: Pencil,
  description: FileText,
  status: CircleDot,
  assignee: UserRound,
  delegate: Bot,
  priority: SignalHigh,
  type: Shapes,
  cycle: RefreshCw,
  start_date: Calendar,
  due_date: Calendar,
  label_add: Tag,
  label_remove: Tag,
  link_add: Link2,
  link_remove: Link2,
  parent: ListTree,
  subtask_add: ListTree,
  subtask_remove: ListTree,
  checklist_add: ListChecks,
  checklist_rename: ListChecks,
  checklist_remove: ListChecks,
  checklist_item_add: ListChecks,
  checklist_item_remove: ListChecks,
  field: Pencil,
  archived: Archive,
  restored: ArchiveRestore,
  github_pr: GitPullRequest,
  agent_started: Bot,
  agent_finished: Bot,
};
