import { Elysia, t } from 'elysia';
import { authContext } from '../shared/auth-context';
import { requireUser } from '../shared/access';
import { entityGuard, guards } from '../shared/guards';
import { HttpError, pgErrorCode } from '../shared/lib';
import { noContent } from '../shared/http';
import { ErrorResponse } from '../shared/responses';
import {
  assertUploadAllowed,
  discardUploadedObject,
  storeUploadedObject,
  uploadObjectKey,
} from '../shared/uploads';
import { createProjectFile, deleteProjectFileById, normaliseFolder } from '../files/store';
import { generateCopy, generateImage } from './generate';
import { listOpenRouterModels } from './models';
import {
  createStudioPost,
  createStudioTemplate,
  deleteStudioPost,
  deleteStudioTemplate,
  getStudioPost,
  getStudioPostProjectId,
  getStudioTemplateProjectId,
  getTemplateForPost,
  listStudioPosts,
  listStudioTemplates,
  studioPostFileIds,
  uniqueFolder,
  updateStudioPost,
  updateStudioTemplate,
  type StudioPostRow,
  type StudioTemplateRow,
} from './store';

const projectParams = t.Object({ projectKey: t.String() });
const idParams = t.Object({ publicId: t.String({ format: 'uuid' }) });

const LayoutSchema = t.Union([
  t.Literal('statement'),
  t.Literal('feature'),
  t.Literal('announcement'),
  t.Literal('overlay'),
]);
const AspectSchema = t.Union([t.Literal('square'), t.Literal('portrait'), t.Literal('story')]);
const ColorSchema = t.String({ pattern: '^#[0-9a-fA-F]{6}$' });

const TemplateResponse = t.Object({
  id: t.String(),
  name: t.String(),
  layout: t.String(),
  aspect: t.String(),
  backgroundColor: t.String(),
  textColor: t.String(),
  accentColor: t.String(),
  fontFamily: t.String(),
  stylePrompt: t.String(),
  credentialId: t.Nullable(t.Number()),
  imageModel: t.String(),
  textModel: t.String(),
  createdAt: t.String(),
  updatedAt: t.String(),
});

const PostResponse = t.Object({
  id: t.String(),
  templateId: t.String(),
  templateName: t.String(),
  createdByName: t.Nullable(t.String()),
  title: t.String(),
  topic: t.String(),
  lead: t.String(),
  headline: t.String(),
  subtext: t.String(),
  chips: t.Array(t.String()),
  ctaLabel: t.String(),
  caption: t.String(),
  imagePrompt: t.String(),
  folder: t.String(),
  sourceImageId: t.Nullable(t.String()),
  renderedImageId: t.Nullable(t.String()),
  status: t.String(),
  createdAt: t.String(),
  updatedAt: t.String(),
});

const ModelsResponse = t.Object({
  image: t.Array(t.Object({ id: t.String(), name: t.String() })),
  text: t.Array(t.Object({ id: t.String(), name: t.String() })),
});

function templateDto(row: StudioTemplateRow) {
  return {
    id: row.publicId,
    name: row.name,
    layout: row.layout,
    aspect: row.aspect,
    backgroundColor: row.backgroundColor,
    textColor: row.textColor,
    accentColor: row.accentColor,
    fontFamily: row.fontFamily,
    stylePrompt: row.stylePrompt,
    credentialId: row.credentialId,
    imageModel: row.imageModel,
    textModel: row.textModel,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

function postDto(row: StudioPostRow) {
  return {
    id: row.publicId,
    templateId: row.templatePublicId,
    templateName: row.templateName,
    createdByName: row.createdByName,
    title: row.title,
    topic: row.topic,
    lead: row.leadLine,
    headline: row.headline,
    subtext: row.subtext,
    chips: row.chips,
    ctaLabel: row.ctaLabel,
    caption: row.caption,
    imagePrompt: row.imagePrompt,
    folder: row.folder,
    sourceImageId: row.sourceImageId,
    renderedImageId: row.renderedImageId,
    status: row.status,
    createdAt: row.createdAt,
    updatedAt: row.updatedAt,
  };
}

// The bytes are stored labelled as a PNG, so they must actually start like one.
const PNG_SIGNATURE = [137, 80, 78, 71, 13, 10, 26, 10];

function isPng(bytes: Buffer): boolean {
  return PNG_SIGNATURE.every((value, index) => bytes[index] === value);
}

// A post together with the template it is built on, for the routes that generate.
async function loadPostWithTemplate(publicId: string) {
  const post = await getStudioPost(publicId);
  if (!post) throw new HttpError(404, 'Post not found');
  const template = await getTemplateForPost(post.templatePublicId, post.projectId);
  if (!template) throw new HttpError(404, 'Template not found');
  return { post, template };
}

// Stores generated bytes as an ordinary vault file inside the post's folder, so
// everything one post produced sits together in Files.
async function storeInPostFolder(
  post: StudioPostRow,
  userId: string,
  filename: string,
  bytes: Buffer,
  contentType: string,
): Promise<number> {
  const key = uploadObjectKey(post.projectId, 'files', filename);
  await storeUploadedObject(key, bytes, contentType);
  try {
    const file = await createProjectFile({
      projectId: post.projectId,
      uploadedByUserId: userId,
      s3Key: key,
      filename,
      contentType,
      sizeBytes: bytes.length,
      folder: post.folder,
    });
    return file.id;
  } catch (error) {
    await discardUploadedObject(key);
    throw error;
  }
}

async function discardReplacedFile(fileId: number | null): Promise<void> {
  if (fileId == null) return;
  const key = await deleteProjectFileById(fileId);
  if (key) await discardUploadedObject(key);
}

export const studioRoutes = new Elysia({ name: 'studio', detail: { tags: ['Studio'] } })
  .use(authContext)
  .use(guards)
  .macro({
    studioTemplate: entityGuard('studio', 'Template not found', (params) =>
      getStudioTemplateProjectId(params.publicId),
    ),
    studioPost: entityGuard('studio', 'Post not found', (params) =>
      getStudioPostProjectId(params.publicId),
    ),
  })

  .get(
    '/projects/:projectKey/studio/templates',
    async ({ project }) => (await listStudioTemplates(project.id)).map(templateDto),
    {
      params: projectParams,
      permission: ['studio', 'read'],
      response: {
        200: t.Array(TemplateResponse),
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
      },
      detail: { summary: 'List the post templates of a project' },
    },
  )

  .post(
    '/projects/:projectKey/studio/templates',
    async ({ project, body, set }) => {
      const row = await createStudioTemplate({
        projectId: project.id,
        name: body.name,
        layout: body.layout,
        aspect: body.aspect,
        backgroundColor: body.backgroundColor,
        textColor: body.textColor,
        accentColor: body.accentColor,
        fontFamily: body.fontFamily,
        stylePrompt: body.stylePrompt ?? '',
        credentialId: body.credentialId ?? null,
        imageModel: body.imageModel,
        textModel: body.textModel ?? '',
      });
      set.status = 201;
      return templateDto(row);
    },
    {
      params: projectParams,
      permission: ['studio', 'create'],
      body: t.Object({
        name: t.String({ minLength: 1, maxLength: 80 }),
        layout: LayoutSchema,
        aspect: AspectSchema,
        backgroundColor: ColorSchema,
        textColor: ColorSchema,
        accentColor: ColorSchema,
        fontFamily: t.String({ minLength: 1, maxLength: 60 }),
        stylePrompt: t.Optional(t.String({ maxLength: 2000 })),
        credentialId: t.Optional(t.Nullable(t.Number())),
        imageModel: t.String({ minLength: 1, maxLength: 120 }),
        textModel: t.Optional(t.String({ maxLength: 120 })),
      }),
      response: {
        201: TemplateResponse,
        400: ErrorResponse,
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
        409: ErrorResponse,
      },
      detail: { summary: 'Create a post template' },
    },
  )

  .patch(
    '/studio/templates/:publicId',
    async ({ params, body }) => {
      const row = await updateStudioTemplate(params.publicId, body);
      if (!row) throw new HttpError(404, 'Template not found');
      return templateDto(row);
    },
    {
      params: idParams,
      studioTemplate: 'edit',
      body: t.Object({
        name: t.Optional(t.String({ minLength: 1, maxLength: 80 })),
        layout: t.Optional(LayoutSchema),
        aspect: t.Optional(AspectSchema),
        backgroundColor: t.Optional(ColorSchema),
        textColor: t.Optional(ColorSchema),
        accentColor: t.Optional(ColorSchema),
        fontFamily: t.Optional(t.String({ minLength: 1, maxLength: 60 })),
        stylePrompt: t.Optional(t.String({ maxLength: 2000 })),
        credentialId: t.Optional(t.Nullable(t.Number())),
        imageModel: t.Optional(t.String({ minLength: 1, maxLength: 120 })),
        textModel: t.Optional(t.String({ maxLength: 120 })),
      }),
      response: {
        200: TemplateResponse,
        400: ErrorResponse,
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
        409: ErrorResponse,
      },
      detail: { summary: 'Update a post template' },
    },
  )

  .delete(
    '/studio/templates/:publicId',
    async ({ params }) => {
      try {
        const deleted = await deleteStudioTemplate(params.publicId);
        if (!deleted) throw new HttpError(404, 'Template not found');
      } catch (error) {
        if (pgErrorCode(error) === '23503') {
          throw new HttpError(409, 'This template still has posts built on it');
        }
        throw error;
      }
      return noContent();
    },
    {
      params: idParams,
      studioTemplate: 'delete',
      response: {
        204: t.Void(),
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
        409: ErrorResponse,
      },
      detail: { summary: 'Delete a post template' },
    },
  )

  .get(
    '/projects/:projectKey/studio/posts',
    async ({ project }) => (await listStudioPosts(project.id)).map(postDto),
    {
      params: projectParams,
      permission: ['studio', 'read'],
      response: {
        200: t.Array(PostResponse),
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
      },
      detail: { summary: 'List the posts of a project' },
    },
  )

  .post(
    '/projects/:projectKey/studio/posts',
    async ({ project, user, body, set }) => {
      const template = await getTemplateForPost(body.templateId, project.id);
      if (!template) throw new HttpError(404, 'Template not found');

      const folder = await uniqueFolder(project.id, normaliseFolder(body.title) || 'Untitled post');
      const row = await createStudioPost({
        projectId: project.id,
        templateId: template.id,
        createdByUserId: requireUser(user).id,
        title: body.title,
        topic: body.topic ?? '',
        folder,
      });
      set.status = 201;
      return postDto(row);
    },
    {
      params: projectParams,
      permission: ['studio', 'create'],
      body: t.Object({
        templateId: t.String({ format: 'uuid' }),
        title: t.String({ minLength: 1, maxLength: 120 }),
        topic: t.Optional(t.String({ maxLength: 2000 })),
      }),
      response: {
        201: PostResponse,
        400: ErrorResponse,
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
      },
      detail: { summary: 'Create a post' },
    },
  )

  .get(
    '/studio/posts/:publicId',
    async ({ params }) => {
      const row = await getStudioPost(params.publicId);
      if (!row) throw new HttpError(404, 'Post not found');
      return postDto(row);
    },
    {
      params: idParams,
      studioPost: 'read',
      response: {
        200: PostResponse,
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
      },
      detail: { summary: 'Read a post' },
    },
  )

  .patch(
    '/studio/posts/:publicId',
    async ({ params, body }) => {
      const { lead, ...rest } = body;
      const row = await updateStudioPost(params.publicId, {
        ...rest,
        ...(lead === undefined ? {} : { leadLine: lead }),
      });
      if (!row) throw new HttpError(404, 'Post not found');
      return postDto(row);
    },
    {
      params: idParams,
      studioPost: 'edit',
      body: t.Object({
        title: t.Optional(t.String({ minLength: 1, maxLength: 120 })),
        topic: t.Optional(t.String({ maxLength: 2000 })),
        lead: t.Optional(t.String({ maxLength: 200 })),
        headline: t.Optional(t.String({ maxLength: 200 })),
        subtext: t.Optional(t.String({ maxLength: 400 })),
        chips: t.Optional(t.Array(t.String({ minLength: 1, maxLength: 40 }), { maxItems: 3 })),
        ctaLabel: t.Optional(t.String({ maxLength: 40 })),
        caption: t.Optional(t.String({ maxLength: 2200 })),
        imagePrompt: t.Optional(t.String({ maxLength: 2000 })),
        status: t.Optional(t.Union([t.Literal('draft'), t.Literal('ready')])),
      }),
      response: {
        200: PostResponse,
        400: ErrorResponse,
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
      },
      detail: { summary: 'Update a post' },
    },
  )

  .delete(
    '/studio/posts/:publicId',
    async ({ params }) => {
      const row = await deleteStudioPost(params.publicId);
      if (!row) throw new HttpError(404, 'Post not found');
      return noContent();
    },
    {
      params: idParams,
      studioPost: 'delete',
      response: {
        204: t.Void(),
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
      },
      detail: { summary: 'Delete a post' },
    },
  )

  .post(
    '/studio/posts/:publicId/copy',
    async ({ params }) => {
      const { post, template } = await loadPostWithTemplate(params.publicId);
      const { lead, ...copy } = await generateCopy(template, post.topic || post.title);
      const row = await updateStudioPost(post.publicId, { ...copy, leadLine: lead });
      if (!row) throw new HttpError(404, 'Post not found');
      return postDto(row);
    },
    {
      params: idParams,
      studioPost: 'edit',
      response: {
        200: PostResponse,
        400: ErrorResponse,
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
        502: ErrorResponse,
      },
      detail: { summary: 'Generate the text of a post with the model of its template' },
    },
  )

  .post(
    '/studio/posts/:publicId/image',
    async ({ params, user }) => {
      const { post, template } = await loadPostWithTemplate(params.publicId);
      const prompt = post.imagePrompt.trim();
      if (!prompt) throw new HttpError(400, 'The post has no image prompt');

      const image = await generateImage(template, prompt);
      await assertUploadAllowed(post.projectId, image.bytes.length, image.contentType);

      const previous = (await studioPostFileIds(post.publicId)).source;
      const extension = image.contentType === 'image/jpeg' ? 'jpg' : 'png';
      const fileId = await storeInPostFolder(
        post,
        requireUser(user).id,
        `photo.${extension}`,
        image.bytes,
        image.contentType,
      );
      const row = await updateStudioPost(post.publicId, { sourceImageFileId: fileId });
      if (!row) throw new HttpError(404, 'Post not found');
      await discardReplacedFile(previous);
      return postDto(row);
    },
    {
      params: idParams,
      studioPost: 'edit',
      response: {
        200: PostResponse,
        400: ErrorResponse,
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
        413: ErrorResponse,
        502: ErrorResponse,
      },
      detail: { summary: 'Generate the photo of a post with the model of its template' },
    },
  )

  .post(
    '/studio/posts/:publicId/rendered',
    async ({ params, user, body }) => {
      const file = body.file;
      if (!(file instanceof File)) throw new HttpError(400, 'No file uploaded (form field "file")');
      if (file.size === 0) throw new HttpError(400, 'Uploaded file is empty');

      const post = await getStudioPost(params.publicId);
      if (!post) throw new HttpError(404, 'Post not found');

      // Checked against the limits before the upload is held in memory.
      await assertUploadAllowed(post.projectId, file.size, 'image/png');
      const bytes = Buffer.from(await file.arrayBuffer());
      if (!isPng(bytes)) throw new HttpError(400, 'The rendered post must be a PNG');

      const previous = (await studioPostFileIds(post.publicId)).rendered;
      const fileId = await storeInPostFolder(
        post,
        requireUser(user).id,
        'post.png',
        bytes,
        'image/png',
      );
      const row = await updateStudioPost(post.publicId, {
        renderedFileId: fileId,
        status: 'ready',
      });
      if (!row) throw new HttpError(404, 'Post not found');
      await discardReplacedFile(previous);
      return postDto(row);
    },
    {
      params: idParams,
      studioPost: 'edit',
      body: t.Object({ file: t.File() }),
      response: {
        200: PostResponse,
        400: ErrorResponse,
        401: ErrorResponse,
        403: ErrorResponse,
        404: ErrorResponse,
        413: ErrorResponse,
        502: ErrorResponse,
      },
      detail: { summary: 'Store the rendered image of a post in its vault folder' },
    },
  )

  .get('/projects/:projectKey/studio/models', async () => listOpenRouterModels(), {
    params: projectParams,
    permission: ['studio', 'read'],
    response: {
      200: ModelsResponse,
      401: ErrorResponse,
      403: ErrorResponse,
      404: ErrorResponse,
    },
    detail: { summary: 'List the OpenRouter models a template can use' },
  });
